Feature/17 model and repository user
alkemyTech/OT110-Server pull request #10
Opened 2021-11-25 15:38 UTC by bredzio

Buenas turcos,
Paso requerimiento con las modificaciones solicitadas.

Saludos!

2021-11-25 20:52 UTC, turcoamado requested changes
Te marqué dos pavadas, el properties que no debería estar y los getters y setters de la entity, que ya los tenés con Lombok. 
No cierres el PR, actualizá el branch y volvé a pushear, el PR se va a actualizar automáticamente cuando hagas eso

2021-11-25 20:52 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/User.java
> +    @Override
De acá para abajo son todos getters y setters, es lo que te había comentado de la utilización de Lombok. La annotation `@Data` los está incluyendo, por lo que son redundantes

2021-11-25 20:52 UTC, turcoamado commented on src/main/resources/application.properties
> -
Ojo que estás incluyendo el archivo properties!! no debería estar

2021-11-25 21:03 UTC, bredzio commented on src/main/java/com/alkemy/ong/model/User.java
> +    @Override
Perfecto, consulta, sabes que esos metodos que me mencionas me los hace sobreescribir obligatoriamente por implementar la interfaz de "userDetails". Si los quito, me arroja error el ide. Estoy en duda si debo sacar esa interfaz o la mantengo.

2021-11-25 21:10 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/User.java
> +    @Override
Tenes razón! Perdón, no me di cuenta de la implementación.

2021-11-25 21:28 UTC, bredzio commented on src/main/resources/application.properties
> -
Listo, ahi modifique el .gitignore. En teoria no deberia subir el properties.

2021-11-26 13:43 UTC, bredzio commented on src/main/java/com/alkemy/ong/model/User.java
> +    @Override
Listo, properties eliminado

2021-11-26 22:25 UTC, bredzio commented on src/main/java/com/alkemy/ong/model/User.java
> +    @Override
Turco, te consulto, no se si deba modificar algo más, porque no me deja hacer el merge. Dice que hay conflicto con el gitIgnore y sin embargo ya lo elimine.

2021-11-27 16:04 UTC, merged