Feature/98 test endpoints testimonials
alkemyTech/OT110-Server pull request #100
Opened 2021-12-26 23:54 UTC by bredzio

Buenas turco,
te paso lo que hice para el ticket #98 sobre testeos sobres los endpoint de testimonials.
Para avanzar mas rapido, mergee esta rama con mi ticket anterior que era de testeo sobre users por lo que estan los archivos que habia modificado en ese ticket.

Testeos exitosos:
![imagen](https://user-images.githubusercontent.com/85000317/147422724-91f3cb7b-589b-4116-8a42-8aa491877d6d.png)

De paso te paso la cobertura sobre los endpoints tanto del controlador de testimonios como de usuarios:
![imagen](https://user-images.githubusercontent.com/85000317/147422689-9bec2beb-c2e2-4619-a821-40e170b45935.png)

Saludos!

2021-12-27 03:47 UTC, turcoamado requested changes
Te hice dos comentarios pero relacionado a lo mismo

2021-12-27 03:47 UTC, turcoamado commented on src/test/java/com/alkemy/ong/integration/testimonial/TestimonialCreateTest.java
> +        TestimonialRequest testimonialRequest = generateTestimonialRequest();
Fijate que esta línea la repetis en los tres test, para evitar eso se puede hacer uso de la annotation @BeforeEach, escribís un método bajo esa annotation y lo que sucede es que se ejecuta ese bloque de código antes de cada test, sirve justamente para inicializar objetos comunes a los test que se van a realizar en esa clase.

2021-12-27 03:47 UTC, turcoamado commented on src/test/java/com/alkemy/ong/integration/testimonial/TestimonialUpdateTest.java
> +        TestimonialRequest testimonialRequest = generateTestimonialRequest();
Lo mismo que te comenté en una clase anterior, tenes varias veces líneas para inicializar un objeto del tipo TestimonialRequest.

También quizás podrías usarlo para el método login(), si queres probalo y me contas.

2021-12-28 00:14 UTC, bredzio commented on src/test/java/com/alkemy/ong/integration/testimonial/TestimonialUpdateTest.java
> +        TestimonialRequest testimonialRequest = generateTestimonialRequest();
Buenisimo turco, ahi lo probe y lo corregi en todos los metodos que pude.
gracias por la data!

2021-12-30 03:29 UTC, turcoamado approved these changes
Buenísimo Bruno!

2021-12-30 12:55 UTC, merged