Feature/37 end point to update public data of the organization
alkemyTech/OT110-Server pull request #22
Opened 2021-11-28 18:46 UTC by GabrielPilag

Turco te paso la info de lo que hice, como hablamos ayer no hice un post porque pedía una actualización, terminé haciendo un patch porque me pareció lo que mejor funcionalidad le daba, ya que consideré que solo existe una organización.
En el patch tuve en consideración la actualización parcial de los datos, por lo que se puede enviar un campo, por ejemplo “name”, y no enviarse ningún otro para actualizar únicamente ese mismo. También validé el formato de los datos y los campos que no pueden ser null. Además, solo actualizo la fecha de actualización si se modificó algún campo. Espero que esté completo, cualquier cosa estoy a la escucha de posibles mejoras o bug que pudiera tener.

2021-11-29 16:52 UTC, turcoamado requested changes
Está muy bueno tu PR, te marqué algunas cosas pero como oportunidad de mejora más que nada. Por el tema de los mensajes es algo que tienen que coordinar también, o en realidad el primero que lo implemente avisarle a los demás para que puedan hacerlo todos

2021-11-29 16:52 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/OrganizationController.java
> +    @PreAuthorize("hasAnyRole('ROLE_ADMIN')")
Acá estaría bueno poder utilizar un Enum como hablamos la otra vez, para no tener que hardcodear el string con el rol

2021-11-29 16:52 UTC, turcoamado commented on src/main/java/com/alkemy/ong/dto/OrganizationRequest.java
> +    @Pattern(regexp=".+@.+\\.[a-z]+", message="Invalid email address")
Muy bueno que hayas utilizado una regex para validar el mail. Otra forma puede ser utilizando la annotation @Email(message="Please provide a valid email address")

2021-11-29 16:52 UTC, turcoamado commented on src/main/java/com/alkemy/ong/exception/NotFoundException.java
> +package com.alkemy.ong.exception;
Esto también está genial! Es la idea empezar a manejar las excepciones de forma centralizada, y tenerlas así es una buena práctica.

2021-11-29 16:52 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +        final Long organizationId = 1L;//se considera que solo hay una organización
Lo que convendría hacer en este caso es un get desde la BD, llamas a un método del repository que te traiga el primer registro que encuentre, porque suponete que alguien borra desde la base el registro y luego mete otro, o se inserta uno y se borra el que tenia id 1. Ya se que es ambiguo, pero es siempre mejor práctica evitar el hardcode.

2021-11-29 16:52 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +                                                        .orElseThrow(()-> new NotFoundException(String.format("cannot find organization with id %s", organizationId)));
Genial que hayas utilizado una expresión lambda!! Lo que si te diría que se puede mejorar es la forma en la que le enviamos los mensajes al cliente que consume nuestro endpoint, en vez de mandar un mensaje hardcodeado podemos tenerlos tabulados en un messages.properties por ejemplo, y de esa manera reutilizarlos, o hasta incluso traducirlos si el día de mañana la aplicación necesita soportar otro idioma.
Te dejo unos links que te pueden orientar con respecto a eso, la idea es crear un bean donde se configure y luego implementarlo en todos los lugares donde vamos a estar enviando mensajes hacia los endpoints, por ejemplo los de errores.
https://zetcode.com/spring/messagesource/
https://looksok.wordpress.com/tag/message-properties/

2021-11-29 16:52 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +                                                        .orElseThrow(()-> new NotFoundException(String.format("cannot find organization with id %s", organizationId)));
Aplicable a las líneas 59 y 70

2021-11-29 16:52 UTC, turcoamado commented on src/main/java/com/alkemy/ong/util/JacksonConfig.java
> +package com.alkemy.ong.util;
Esto donde lo estás utilizando?

2021-11-29 18:52 UTC, GabrielPilag commented on src/main/java/com/alkemy/ong/controller/OrganizationController.java
> +    @PreAuthorize("hasAnyRole('ROLE_ADMIN')")
ah si no me acordaba! le pregunto a mis compañeros que hicieron la parte de security si ya lo implementaron, sino lo implemento yo!

2021-11-29 18:54 UTC, GabrielPilag commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +        final Long organizationId = 1L;//se considera que solo hay una organización
buenisimo! no me di cuenta que podía pasar eso y encima es muy probable que pase! lo corrijo y lo subo, gracias!

2021-11-29 18:55 UTC, GabrielPilag commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +                                                        .orElseThrow(()-> new NotFoundException(String.format("cannot find organization with id %s", organizationId)));
dale lo estudio un poco porque nunca lo hice de esa forma! cualquier cosa te consulto si no me sale

2021-11-29 19:21 UTC, GabrielPilag commented on src/main/java/com/alkemy/ong/util/JacksonConfig.java
> +package com.alkemy.ong.util;
Este lo utilizo para la deserialización del json para poder tener el estado undefined con el wrapper JsonNullable para poder distinguir entre un undefined y un null en los campos que pueden ser null

2021-11-29 23:40 UTC, turcoamado commented on src/main/java/com/alkemy/ong/util/JacksonConfig.java
> +package com.alkemy.ong.util;
Bien perfecto!

2021-11-29 23:54 UTC, turcoamado requested changes

2021-11-29 23:54 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/OrganizationController.java
> +        return new ResponseEntity<OrganizationResponse>(iOrganizationService.updatePublicData(organization), HttpStatus.OK);
Algo que acabo de ver y antes se me pasó perdón, es que te faltó el status http en caso de error

2021-11-30 00:35 UTC, GabrielPilag commented on src/main/java/com/alkemy/ong/controller/OrganizationController.java
> +        return new ResponseEntity<OrganizationResponse>(iOrganizationService.updatePublicData(organization), HttpStatus.OK);
Ah yo iba a hacer un handler de las excepciones pero no sabia si hacerlo ahora o si había una tarjeta mas adelante, con el handler normalmente manejo el formato del mensaje de error para que sea siempre igual y el status http del caso de error. Como debería hacerlo?

2021-12-01 13:57 UTC, turcoamado approved these changes

2021-12-01 13:57 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/OrganizationController.java
> +        return new ResponseEntity<OrganizationResponse>(iOrganizationService.updatePublicData(organization), HttpStatus.OK);
Creo que te respondi esto en una de las reuniones, pero esta perfecto el uso de un handrler para las excepciones, es la mejor manera de hacerlo y yo siempre les digo de intentar manejarlo de esa manera.

2021-12-01 14:24 UTC, merged