feature/35-Endpoint List Users as Adminitrator
alkemyTech/OT110-Server pull request #23
Opened 2021-11-28 22:36 UTC by Valle1989

Turco entrego mi tarea asignada. En mi caso tuve que hacer el endpoint que devuelva un listado de Usuarios y que sólo puede ser accedido por aquellos Usuarios que tengan el rol de Administrador. Quedo a la espera de tu devolución.

2021-11-30 00:00 UTC, turcoamado requested changes

2021-11-30 00:00 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
A uno de  tus compañeros le hice este mismo comentario, acá es preferible utilizar el enum del que hablamos en alguna daily, la razón? No tener nada hardcoded, siempre es buena práctica evitar el código hardcodeado

Estás probando qué sucede si efectivamente el endpoint es ejecutado por alguien que no tenga el rol admin?

2021-11-30 00:00 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/UserServiceImpl.java
> +        List<UserDto> userDto = userRepository.findAll().stream()
Muy buena la implementación de la expresión lambda acá!

2021-12-01 14:34 UTC, turcoamado approved these changes
Te lo dejo como aprobado, luego fijate si podes cambiar los mensajes para usar lo que implementaron o si tenes excepciones para usar el handler. Pero podes hacerlo mas adelante tambien, asi no nos vamos atrasando tanto con los merge y las demas tareas

Y una cosa mas, proba de sacarle el package completo cuando usas el Enum, queda mas prolijo, lo escribirias como RoleEnum.ADMIN y en los imports te pone el package

2021-12-01 14:34 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +    @PreAuthorize("hasAnyRole(T(com.alkemy.ong.security.RoleEnum).ADMIN)")
Bien! Pero no te dejo ponerlo sin necesidad de escribir todo el package? directamente como RoleEnum.ADMIN?

2021-12-01 17:09 UTC, Valle1989 commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +    @PreAuthorize("hasAnyRole(T(com.alkemy.ong.security.RoleEnum).ADMIN)")
En mi caso sólo puse directamente esa línea porque Gabi me dijo que la creación del Enum la había hecho él, y supuse que cuándo mergeara mi parte ya no haría falta hacerla. Por eso no es que no me haya dejado ponerlo sin la necesidad de escribir todo el package sino que tuve la oportunidad de probarlo. Pero investigué que también se puede hacer de la manera que decís vos, así que sería cuestión de modificarlo.

2021-12-01 20:35 UTC, merged