Feature/23 endpoint get organization
alkemyTech/OT110-Server pull request #24
Opened 2021-11-29 00:46 UTC by mayorgaclara

GET to /organization/public

2021-11-29 23:44 UTC, turcoamado requested changes

2021-11-29 23:44 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/OrganizationController.java
> +    private IOrganizationService IOrganizationService;
El nombre de la variable debe comenzar con minúscula, el de la clase está bien. Es una cuestión de buenas prácticas nada más, no quiere decir que no vaya a funcionar

2021-11-29 23:44 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/OrganizationController.java
> +        List<OrganizationPublicDto> organizations = this.IOrganizationService.getAllOrganizations();
Este this no sería necesario, si directamente se pone la variable y el método debería funcionar lo mismo. Probalo por las dudas.

2021-11-29 23:44 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/serviceImpl/IOrganizationServiceImpl.java
> +        for (Organization entity : entities) {
Esto también se puede realizar mediante una expresión lambda, utilizando stream(), no está mal de todos modos, no es para que lo cambies sino para que lo tengas en cuenta

2021-11-29 23:44 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/serviceImpl/IOrganizationServiceImpl.java
> +    public List<OrganizationPublicDto> getAllOrganizations() {
Mismo comentario que en el controller, no es necsario utilizar el this

2021-11-30 00:02 UTC, turcoamado requested changes

2021-11-30 00:02 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/OrganizationController.java
> +        return ResponseEntity.ok().body(organizations);
En caso de fallar te está faltando la respuesta http, y en realidad el manejo completo, asumo que te explotaría y verías el log por la consola nada más.

2021-11-30 02:05 UTC, mayorgaclara commented on src/main/java/com/alkemy/ong/controller/OrganizationController.java
> +        return ResponseEntity.ok().body(organizations);
Agregué la respuesta a un error interno, entiendo que en el GET no surgirían errores 400, 0 404 puede ser?

2021-11-30 02:36 UTC, mayorgaclara commented on src/main/java/com/alkemy/ong/service/serviceImpl/IOrganizationServiceImpl.java
> +        for (Organization entity : entities) {
Perfecto, lo dejo así ahora pero ya estoy estudiando las expresiones lamba. graciass

2021-12-01 14:32 UTC, turcoamado approved these changes
Te lo dejo como aprobado, luego fijate si podes cambiar los mensajes para usar lo que implementaron o si tenes excepciones para usar el handler. Pero podes hacerlo mas adelante tambien, asi no nos vamos atrasando tanto con los merge y las demas tareas

2021-12-01 23:53 UTC, merged