Template de email de Bienvenida
alkemyTech/OT110-Server pull request #27
Opened 2021-11-29 19:46 UTC by adrian010

Templade de email de bienvenida terminado, y configurado

2021-11-30 18:41 UTC, turcoamado requested changes

2021-11-30 18:41 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/WelcomeTemplateService.java
> +    public String setTemplate(String name, String surName) throws EmailException {
surname es una sola palabra, por lo que debería ir escrita como surname, sin la N mayúscula

2021-11-30 18:41 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/WelcomeTemplateService.java
> +            String messageError = "Welcome Email creating failure : " + e.getMessage();
Este mensaje habría que pasarlo a la implementación que realizó (o está haciendo) uno de los chicos, para que no tengamos más mensajes hardcoded en el código

2021-11-30 18:41 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/WelcomeTemplateService.java
> +        return "Email de Bienvenida";
Este mensaje habría que pasarlo a la implementación que realizó (o está haciendo) uno de los chicos, para que no tengamos más mensajes hardcoded en el código

2021-11-30 18:47 UTC, adrian010 commented on src/main/java/com/alkemy/ong/service/WelcomeTemplateService.java
> +            String messageError = "Welcome Email creating failure : " + e.getMessage();
ah ok dale pero como no tengo esa implementacion que hicieron, tuve que hacer eso por ahora

2021-12-01 14:27 UTC, turcoamado approved these changes
Te lo dejo como aprobado, luego fijate si podes cambiar los mensajes para usar lo que implementaron o si tenes excepciones para usar el handler. Pero podes hacerlo mas adelante tambien, asi no nos vamos atrasando tanto con los merge y las demas tareas

2021-12-01 15:08 UTC, merged