Feature/43 category update endpoint
alkemyTech/OT110-Server pull request #36
Opened 2021-12-05 00:59 UTC by alejandroitsoluciones

Buenas Turco aqui hago el PR de mi ticket. Tengo dos dudas y quisiera poder conseguir mas informacion es sobre @PreAuthorize no me gusta como queda esa parte, trate de buscarle la vuelta pero no encontre como hacerlo mejor, estaria bueno si me tiraras alguna ayuda, apunte o enlace donde me pueda apoyar para mejorar en ese detalle. La otra es, cumplen las mismas funciones @PreAuthorize y @Secured...? Dejo capturas del funcionamiento del Endpoint. Saludos.

Aqui se muestra una categoria precargada en la base de datos.
![category_1](https://user-images.githubusercontent.com/62119845/144729207-65d62ed0-cf49-43c3-9800-56337ae0fbed.jpg)

Se crea el Json para modificar la categoria existente.
![category_2](https://user-images.githubusercontent.com/62119845/144729208-0c52a508-1c61-4c44-bc78-e97764d37c6e.jpg)

Se envia el Json y la respuesta se puede ver la categoria actualizada.
![category_3](https://user-images.githubusercontent.com/62119845/144729209-861f5e90-b0d1-4395-a589-8bacd949f2ad.jpg)

Se hace un test de validacion de campos obligatorios como el Name.
![category_4](https://user-images.githubusercontent.com/62119845/144729211-7f6138d6-1d87-4d60-ace1-33cb94d16b09.jpg)

2021-12-06 04:57 UTC, turcoamado requested changes

2021-12-06 04:57 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    @PreAuthorize("hasAnyRole(T(com.alkemy.ong.security.RoleEnum).ADMIN)")
Fijate de utilizar RoleEnum.ADMIN.getName() en vez de ponerle todo el nombre del package, que eso se importe arriba

2021-12-06 04:57 UTC, turcoamado commented on src/main/java/com/alkemy/ong/dto/CategoryDto.java
> +    private String dateCreacion;
ponele el creacion en inglés, dateCreation

2021-12-06 04:59 UTC, turcoamado requested changes

2021-12-06 04:59 UTC, turcoamado commented on src/main/java/com/alkemy/ong/dto/CategoryRequestUpdate.java
> +	private String descripcion;
description en vez de descripcion

2021-12-06 04:59 UTC, turcoamado commented on src/main/java/com/alkemy/ong/dto/CategoryDto.java
>      private String descripcion;
Description en lugar de descripcion

2021-12-06 05:08 UTC, turcoamado commented
Con respecto a tus dudas, @PreAuthorized y @Secured se utilizan para lo mismo, pero @PreAuthorized es más nueva, y soporta algunas cosas que con @Secured no se podían realizar, o eran más complejas. 
Diferencia entre @PreAuthorized y @Secured: https://stackoverflow.com/questions/3785706/whats-the-difference-between-secured-and-preauthorize-in-spring-security-3

Un poco de documentación sobre @PreAuthorized
https://www.concretepage.com/spring/spring-security/preauthorize-postauthorize-in-spring-security

También se puede reemplazar el uso de esta annotation y proteger las rutas a cada endpoint desde la configuración de JWT. Ambos casos estarían bien.

2021-12-06 12:30 UTC, alejandroitsoluciones commented on src/main/java/com/alkemy/ong/dto/CategoryDto.java
> +    private String dateCreacion;
Uuuuff si, no me di cuenta. Ahora lo arreglo.

2021-12-06 20:14 UTC, alejandroitsoluciones commented on src/main/java/com/alkemy/ong/dto/CategoryDto.java
>      private String descripcion;
Todo listo Turco, creo que quedo bien.

2021-12-07 04:39 UTC, turcoamado requested changes

2021-12-07 04:39 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/SecurityConstant.java
> +	public static final String ADMIN = "hasAnyRole(T(com.alkemy.ong.security.RoleEnum).ADMIN)";
Puede ser una alternativa, pero no toma directamente `RoleEnum.ADMIN.getName()` como lo estás utilizando en la clase SecurityConfig, línea 52? Para poner eso sobre los endpoints y no tener que crear una interface más.

2021-12-07 12:41 UTC, alejandroitsoluciones commented on src/main/java/com/alkemy/ong/security/SecurityConstant.java
> +	public static final String ADMIN = "hasAnyRole(T(com.alkemy.ong.security.RoleEnum).ADMIN)";
Buen dia Turco, no, la verdad que no funciona si le pongo directamente el RoleEnum asi, porque el @PreAutorized se queja de que no es una constante. De todas formas la solucion la hice asi porque Gabriel habia compartido algo asi pero no estaba seguro de si funcionaba o no. Entonces yo lo implemente y lo comprobe que si funciona, y lo implementamos de forma diferente porque el implementa la interfaz en el controlador y lo que yo hice fue poner el nombre de la interfaz y la variable constante con la expresion.

![category_5](https://user-images.githubusercontent.com/62119845/145029895-8e9baf31-7dd8-4ad1-9fe9-a4b1e686974d.jpg)

De todas formas creo que voy a sacar esa linea 52 del SecurityConfig porque ayer nos reunimos y decidimos que la seguridad iba a ser distribuida con el @PreAutorized

2021-12-07 14:59 UTC, turcoamado approved these changes
Estamos OK entonces, definan si lo de los @PreAuthorized lo realizan como codeaste vos o como lo realizó Gabi y luego de eso mergea tranqui. Pero intentemo que quede de una única forma.

2021-12-07 14:59 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/SecurityConstant.java
> +	public static final String ADMIN = "hasAnyRole(T(com.alkemy.ong.security.RoleEnum).ADMIN)";
Perfecto! Bueno, me queda claro. Entonces definan una de las dos maneras así tenemos consistencia y adoptamos esa única forma de realizarlo para futuros endpoints

2021-12-07 15:32 UTC, merged