Feature/39 reusable image upload service
alkemyTech/OT110-Server pull request #40
Opened 2021-12-06 16:04 UTC by GabrielPilag

2021-12-06 16:05 UTC, GabrielPilag commented on src/main/java/com/alkemy/ong/aws/AWSS3Controller.java
> +public class AWSS3Controller implements Controllers {
Este controller lo hice considerando que las imagenes se van a subir desde el front y luego desde el front harían un put de la imagen en las tablas mediante los servicios en los controller correspondientes

2021-12-06 16:06 UTC, GabrielPilag commented on src/main/java/com/alkemy/ong/controller/Controllers.java
> +public interface Controllers {
Esta interface la hice para simplicar el uso de los roles en los controllers, no se si es buena practica

2021-12-06 16:07 UTC, GabrielPilag commented on src/main/java/com/alkemy/ong/exception/ApiExceptionHandler.java
> +	public ExceptionMessage  returnErrorAmazonServiceException(AmazonServiceException e){
![ErrorAmazon](https://user-images.githubusercontent.com/84400475/144880424-cceb9042-4aba-4cd8-ba68-c6610d76058c.png)

2021-12-06 16:10 UTC, GabrielPilag commented on src/main/resources/application.yml
> +server:
este estaba en el gitignore, recien lo veo, se ve que en el hotfix se cambio el gitignore, ya lo volví a agregar

2021-12-06 16:11 UTC, GabrielPilag commented on src/main/java/com/alkemy/ong/aws/AWSS3ServiceImpl.java
> +public class AWSS3ServiceImpl implements IAWSS3Service {
![AWSS3UploadFileOK](https://user-images.githubusercontent.com/84400475/144881102-3026dbf7-5942-4963-9843-1a57a8e65e6c.png)

2021-12-06 16:12 UTC, GabrielPilag commented on src/main/java/com/alkemy/ong/aws/AWSS3ServiceImpl.java
> +        if(multipartFile.isEmpty()){
![AWSS3UploadFileExceptionEmpty](https://user-images.githubusercontent.com/84400475/144881154-5d04ab27-47fe-490c-99d2-4e14a4418600.png)

2021-12-06 16:12 UTC, GabrielPilag commented on src/main/java/com/alkemy/ong/aws/AWSS3ServiceImpl.java
> +        if (!isSupportedContentType(contentType)) {
![AWSS3UploadFileException](https://user-images.githubusercontent.com/84400475/144881219-be0d3ca4-516b-47bc-a967-9372cade5ecb.png)

2021-12-07 04:52 UTC, turcoamado requested changes

2021-12-07 04:52 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/Controllers.java
> +public interface Controllers {
Lo vi en en un PR de un compañero, no se si habrá partido desde Alejandro, no se si trabajaron juntos y salió de un commit tuyo o fue mera casualidad.
Lo que le comenté es que puede ser una buena alternativa, pero me parece que se están complicando, deberían poder utilizar directamente `RoleEnum.ADMIN.getName()`, con eso tendría que alcanzar. Probá si te funciona escribiendo de esa forma sobre los endpoints y si es así entonces no sería necesaria la interface que estás proponiendo.

2021-12-07 13:46 UTC, GabrielPilag commented on src/main/java/com/alkemy/ong/controller/Controllers.java
> +public interface Controllers {
Turco, si se me ocurrió hacerlo de esa forma porque al poner RoleEnum.ADMIN.getName() me dice que el atributo dentro del annotation tiene que ser una constante. Le compartí a Ale la idea y él lo hizo en otra paquete, quedamos ayer con los compañeros que si sirve esta implementación dejabamos como lo había organizado Ale porque esta dentro del paquete de seguridad.

2021-12-07 15:00 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/Controllers.java
> +public interface Controllers {
Si es verdad, perdón! Ale me dijo lo mismo. Quedamos OK entonces, simplemente tengan cuidado de realizar todos la misma implementación, porque vi que Gabi tenía otra

2021-12-07 15:01 UTC, turcoamado approved these changes
**[EDIT]**
Lo confirmé con Ale, lo que te dije yo no va a funcionar. Tengan el cuidado de que quede siempre la misma implementación de lo que plantearon que está muy bien.

2021-12-07 17:53 UTC, merged