Feature/60 sildes endpoint publico
alkemyTech/OT110-Server pull request #69
Opened 2021-12-12 03:45 UTC by mayorgaclara

En esta tarea agrego la lista de slides en el endpoint publico de la organización.
Para ello agregué dentro de OrganizationModel una relación OneToMany con slides. Esto me generó una tabla organizations_slides, creí que eso solo ocurria en las ManyToMany pero leyendo la documentación me indicaba que esta OK. Es así? 

Al hacer get del endpoint de organizaciones muestra el listado de slides:

![image](https://user-images.githubusercontent.com/71157666/145699376-f949e542-29d5-474d-ad80-18d919ca28d0.png)

Además, agregué los mappers de los archivos involucrados en este ticket. Mañana nos reunimos con el equipo para refactorizar el resto.

2021-12-12 17:36 UTC, turcoamado requested changes

2021-12-12 17:36 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Organization.java
> +
Te debe estar generando la tabla extra quizás porque no estás especificando con que columna tiene que matchear (usando la annotation @JoinColumn). Porque no, no debería generarte una tabla intermedia

2021-12-12 19:54 UTC, mayorgaclara commented on src/main/java/com/alkemy/ong/model/Organization.java
> +
Listo, solucionado, ya no hay tabla intermedia, si no que está la FK en slides con organization_id.
Adjunto información de Workbench y Postman funcionando:

![image](https://user-images.githubusercontent.com/71157666/145727416-3b362529-d84f-45d5-9e83-e85fa070de6e.png)


![image](https://user-images.githubusercontent.com/71157666/145727382-db145e86-3dad-45b4-aa22-9e472034275e.png)

2021-12-13 04:00 UTC, turcoamado approved these changes
Un espectáculo Clara!

2021-12-13 12:44 UTC, merged