EndPoint 55 List Slide
alkemyTech/OT110-Server pull request #73
Opened 2021-12-14 19:43 UTC by luifa04

turco, te dejo mil ticket de la semana pasado. hoy me pongo al dia.

Caso de lista de slides vacia.

![lista vacia](https://user-images.githubusercontent.com/88746660/146068364-25bd3e36-460e-4839-93d9-00ef343122de.PNG)

caso de exito.
![exito](https://user-images.githubusercontent.com/88746660/146068426-b8e2b935-abd2-4723-a26c-c08554175c8a.PNG)

2021-12-15 04:46 UTC, turcoamado requested changes
Está casi perfecto, pero lo mismo que le comenté a Ale. 
A pesar de que la lista está vacía no correspondería mostrar un 404 porque no es un error, es un caso de éxito solo que no tiene datos, se debería mostrar un 200 pero con el mensaje de que está vacío.

2021-12-15 13:36 UTC, luifa04 commented
![caso exito lista vacia](https://user-images.githubusercontent.com/88746660/146196307-da58e349-16c0-4fe7-8e32-eca924b36f54.PNG)
![exito con cambios](https://user-images.githubusercontent.com/88746660/146196349-41be35ee-e760-4828-b835-e2906c80779d.PNG)

2021-12-16 13:50 UTC, turcoamado approved these changes

2021-12-17 13:01 UTC, turcoamado approved these changes

2021-12-17 16:19 UTC, merged