added exception message
alkemyTech/OT110-Server pull request #77
Opened 2021-12-16 00:27 UTC by GabrielPilag

Turco te mando este PR que surgió de juntarnos con los compañeros para ver un problema en la parte de seguridad, con los roles.

2021-12-16 14:00 UTC, turcoamado requested changes
ünicamente cambiale el system.out por un log y estamos

2021-12-16 14:00 UTC, turcoamado commented on src/main/java/com/alkemy/ong/exception/ApiExceptionHandler.java
> +		System.out.println(e.getCause());
por que están usando un system.out? Si quieren algo por consola lo mejor es hacerlo en un Log

2021-12-16 14:27 UTC, GabrielPilag commented on src/main/java/com/alkemy/ong/exception/ApiExceptionHandler.java
> +		System.out.println(e.getCause());
ah se me paso, lo habíamos puesto para probar no más, lo borro

2021-12-17 13:02 UTC, turcoamado approved these changes

2021-12-17 20:15 UTC, merged