Feature/82 add pagination to members
alkemyTech/OT110-Server pull request #79
Opened 2021-12-16 12:40 UTC by GabrielPilag

Turco te dejo mi PR me tocaba la tarea 82- Agregar paginación a Miembros.
![MembersPagination3](https://user-images.githubusercontent.com/84400475/146373907-b7854abd-301f-4fdb-916e-abb8d4c4da8b.png)
![MembersException](https://user-images.githubusercontent.com/84400475/146373914-cf50bdbb-9a65-44f6-a40d-8920d703d24a.png)
![MembersPagination1](https://user-images.githubusercontent.com/84400475/146373916-dadfa4eb-55ea-4632-a0c9-c70cc17e2aec.png)
![MembersPagination2](https://user-images.githubusercontent.com/84400475/146373919-88d06c71-64fb-43a3-ac41-03a0ec0d514c.png)

2021-12-16 17:07 UTC, turcoamado requested changes
Está muy bien! Te marqué únicamente el error, debe recibir un 404 y no un 400

2021-12-16 17:07 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/MemberServiceImpl.java
> +			throw new IllegalArgumentException(memberLastPage + lastPage);
Esta exception está devolviendo el 400? Porque debería devolver un 404 en este caso, estas buscando algo y no lo encontró, el 400 es cuando el servidor no puede interpretar lo que se le envía, no es el caso, acá lo que sucede es que la url enviada no arroja resultados, para esto está el 404

2021-12-16 18:49 UTC, GabrielPilag commented on src/main/java/com/alkemy/ong/service/impl/MemberServiceImpl.java
> +			throw new IllegalArgumentException(memberLastPage + lastPage);
excelente Turco, ya lo cambie por 404!

2021-12-17 13:05 UTC, turcoamado approved these changes
Siempre y cuando esa excepción se use para algo así, un not found. Si además se está usando para otra cosa donde el 400 está bien entonces habría que crear una nueva

2021-12-17 20:23 UTC, merged