Feature/79 endpoint list comments
alkemyTech/OT110-Server pull request #86
Opened 2021-12-18 00:31 UTC by Valle1989

Turco te dejo mi segundo ticket, en este caso tenía que listar los comentarios en base a los posteos o noticias.
![newsOne](https://user-images.githubusercontent.com/65571650/146622300-b6fe04e8-f556-49e2-80df-138ecef9effd.jpg)
Noticia con id 1 y sus respectivos comentarios

![newsTwo](https://user-images.githubusercontent.com/65571650/146622321-e608caa0-c561-444d-ab06-b93b76d09c44.jpg)
Noticia con id 2 y sus respectivos comentarios

![newsTree](https://user-images.githubusercontent.com/65571650/146622340-9228a465-afb4-4993-a938-196daab094db.jpg)
Noticia con id 3 y sus respectivos comentarios

![newsFour](https://user-images.githubusercontent.com/65571650/146622359-69824945-adbf-48d8-9ba4-979d68d7d150.jpg)
Noticia con id 4 y sus respectivos comentarios

2021-12-20 22:02 UTC, turcoamado requested changes

2021-12-20 22:02 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java
> +                .filter(comment -> comment.getNews().getId() == id)
Si el id no existe trae la lista vacia entiendo, y arrojaria el EmtpyDataException, verdad? No esta mal, puede ser válido, pero yo lo que haría sería lanzar otro tipo de excepción, un 404 indicando que la la noticia no existe, únicamente en el caso de que no exista, no si existe y la misma no tiene comentarios, eso esta bien resuelto.

2021-12-20 23:47 UTC, Valle1989 commented on src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java
> +                .filter(comment -> comment.getNews().getId() == id)
Ok Turco, no me había dado cuenta. Ya lo corrijo.

2021-12-21 00:22 UTC, Valle1989 commented on src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java
> +                .filter(comment -> comment.getNews().getId() == id)
Ahí lo modifiqué Turco, nose si esta correcto. Cualquier cosa avisame y lo modifico si hace falta.

2021-12-21 12:38 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java
> +                .filter(comment -> comment.getNews().getId() == id)
La validación está bien, pero lo anterior sigue funcionando? Me refiero a que si no existen comentarios, muestra un 200 pero el mensajes de que no hay comentarios?
Yo le dejaría este if también, pero no probé el código por eso te consulto, lo voy leyendo nada más.
`if(comments.isEmpty()){
            throw new EmptyDataException(contactListEmpty);`

2021-12-21 12:46 UTC, Valle1989 commented on src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java
> +                .filter(comment -> comment.getNews().getId() == id)
No, eso lo saqué. Después me di cuenta que debería haberlo dejado porque no estaría mandando el msj de la lista vacía en caso de que exista la noticia pero no tenga comentarios. Así que lo agrego otra vez y pruebo que funcione todo bien.

2021-12-21 23:50 UTC, Valle1989 commented on src/main/java/com/alkemy/ong/service/impl/CommentServiceImpl.java
> +                .filter(comment -> comment.getNews().getId() == id)
Listo Turco, probé todo y funciona.

2021-12-22 12:01 UTC, turcoamado approved these changes

2021-12-22 22:17 UTC, merged